method: closed_loop_shift
kwargs:
  lag: 1
  horizon: 1
  model_dim: 256
  n_kernels: 128
  kernel_dim: 64
  kernel_repeat: 9
  n_heads: 1
  head_dim: 1
  kernel_weights: null
  kernel_init: normal
  kernel_train: true
  skip_connection: false
  norm_order: 1
  use_initial: false
